flamingo:
  router:
    path: /en

# Configure the module flamingo-commerce-adapter-standalone
flamingo-commerce-adapter-standalone:
  enableIndexing: true
  csvCommerce:
    productCsvPath: "ressources/products/products_en.csv"
    locale: "en_GB"
    currency: "GBP"
    allowedImageResizeParamaters: "500x,200x,700x,40x"
