flamingo:
  router:
    path: /en

# Configure the modules flamingoCommerceAdapterStandalone
flamingoCommerceAdapterStandalone:
  csvindexing:
    products:
      file:
        path: "ressources/products/products_en.csv"
        delimiter: ","
    categories:
      file:
        path: "ressources/products/categories.csv"
        delimiter: ","
    locale: "en_GB"
    currency: "GBP"
